### ISSUE TITLE
Realm sonic issue

### ISSUE THREAD

**Issue by alter171** [Arexon/geometry-fix#3] opened 2022-03-24 21:56 UTC
I am experiencing the same issues as the other post on here, when I turn on the mod it causes the realm to enable a sonic resource pack. I have tested it and it only occurs when the mod is activated for realms specifically, not normal worlds.

**Comment by Arexon** [comment] 2022-03-24 22:37
Duplicate of #2

**Closed by Arexon** 2022-03-24 22:37 UTC
Labels: duplicate
